import os
import numpy as np
import pandas as pd
import torch

from sklearn.metrics import roc_auc_score, average_precision_score, f1_score, precision_score, recall_score

from src.dataset.dataset_loader_relationwise import build_heterodata_full, split_heterodata
from src.support.utils import set_random_seed, get_base_dir


# ============================================================
# Experimental setting
# ============================================================

DATASETS = ["politifact", "mumin"]
SEEDS = [42, 96, 132, 123, 2026]

INTERACTION_MODE = "any"

VAL_RATIO = 0.15
TEST_RATIO = 0.25
EVAL_NEG_RATIO = 1.0

# Same common configuration used in Table 2
DISJOINT_TRAIN_RATIO = 0.2
THRESHOLD_METRIC = "f1-macro"


# ============================================================
# Metrics
# ============================================================

def compute_metrics(labels, scores, threshold):

    pred = (scores >= threshold).astype(int)

    return {
        "auc": roc_auc_score(labels, scores),
        "ap": average_precision_score(labels, scores),
        "f1-binary": f1_score(labels,pred, zero_division=0),
        "f1-macro": f1_score(labels,pred, average="macro",zero_division=0),
        "precision": precision_score(labels, pred, zero_division=0),
        "recall": recall_score(labels, pred, zero_division=0),
    }


"""
Same validation-threshold logic used by the GAT experiments,
but directly applied to non-parametric popularity scores.
"""
def find_best_threshold_from_scores(labels, scores, optimization_metric="f1-macro"):

    # Descending ranking by score.
    sorting_indices = np.argsort(-scores, kind="mergesort")

    sorted_scores = scores[sorting_indices]
    sorted_labels = labels[sorting_indices]

    positive_mask = sorted_labels == 1
    negative_mask = sorted_labels == 0

    cumulative_tp = np.cumsum(positive_mask)
    cumulative_fp = np.cumsum(negative_mask)

    total_positives = cumulative_tp[-1]
    total_negatives = cumulative_fp[-1]

    # Threshold changes only when the score changes.
    last_index_per_score = np.concatenate(
        [np.where(sorted_scores[:-1]!= sorted_scores[1:])[0], np.array([len(sorted_scores) - 1])]
    )

    candidate_thresholds = sorted_scores[last_index_per_score]

    tp = cumulative_tp[last_index_per_score]
    fp = cumulative_fp[last_index_per_score]

    fn = total_positives - tp
    tn = total_negatives - fp

    positive_denominator = 2 * tp + fp + fn

    f1_binary = np.divide(
        2 * tp,positive_denominator,
        out=np.zeros_like(tp, dtype=float),
        where=positive_denominator != 0
    )

    negative_denominator = 2 * tn + fn + fp

    f1_negative = np.divide(
        2 * tn,
        negative_denominator,
        out=np.zeros_like(tn, dtype=float),
        where=negative_denominator != 0,
    )

    f1_macro = (f1_binary + f1_negative) / 2

    if optimization_metric == "f1-binary":
        values = f1_binary
    else:
        values = f1_macro

    best_index = int(np.argmax(values))

    return float(candidate_thresholds[best_index])


# ============================================================
# Popularity baseline
# ============================================================

"""
score(u, n) = degree_train(n)

The degree is computed exclusively from target links
visible in the training message-passing graph.
"""
def get_popularity_scores(train_data, eval_data, target_edge_type):


    # E^+_{train,mp}
    train_edge_index = train_data[target_edge_type].edge_index

    target_node_type = target_edge_type[2]

    num_target_nodes = train_data[target_node_type].num_nodes

    # Target/news node IDs for visible train interactions.
    target_nodes = train_edge_index[1]

    popularity = torch.bincount(target_nodes,minlength=num_target_nodes).float()

    # Positive + negative pairs generated by RandomLinkSplit.
    edge_label_index = eval_data[target_edge_type].edge_label_index

    labels = eval_data[target_edge_type].edge_label.detach().view(-1).cpu().numpy().astype(int)


    eval_target_nodes = edge_label_index[1]

    scores = popularity[eval_target_nodes].cpu().numpy()

    return labels, scores


# ============================================================
# Run
# ============================================================

all_results = []

for dataset_name in DATASETS:

    print("\n")
    print("=" * 70)
    print(f"POPULARITY BASELINE - {dataset_name}")
    print("=" * 70)

    dataset_results = []

    for seed in SEEDS:

        print(f"\nSeed: {seed}")

        # Important: same RNG state used to generate the corresponding RandomLinkSplit.
        set_random_seed(seed)

        data, target_edge_type, reverse_target_edge_type = (
            build_heterodata_full(
                dataset_name=dataset_name,
                interaction_mode=INTERACTION_MODE,
            )
        )

        train_data, val_data, test_data = (
            split_heterodata(
                data=data,
                target_edge_type=target_edge_type,
                reverse_target_edge_type=reverse_target_edge_type,
                val_ratio=VAL_RATIO,
                test_ratio=TEST_RATIO,
                eval_neg_sampling_ratio=EVAL_NEG_RATIO,
                disjoint_train_ratio=DISJOINT_TRAIN_RATIO,
            )
        )

        # ----------------------------
        # Validation
        # ----------------------------

        val_labels, val_scores = (
            get_popularity_scores(
                train_data=train_data,
                eval_data=val_data,
                target_edge_type=target_edge_type,
            )
        )

        best_threshold = (
            find_best_threshold_from_scores(
                labels=val_labels,
                scores=val_scores,
                optimization_metric=THRESHOLD_METRIC,
            )
        )

        val_metrics = compute_metrics(
            labels=val_labels,
            scores=val_scores,
            threshold=best_threshold,
        )

        # ----------------------------
        # Test
        # ----------------------------

        test_labels, test_scores = (
            get_popularity_scores(
                train_data=train_data,
                eval_data=test_data,
                target_edge_type=target_edge_type,
            )
        )

        test_metrics = compute_metrics(
            labels=test_labels,
            scores=test_scores,
            threshold=best_threshold,
        )

        result = {
            "dataset_name": dataset_name,
            "seed": seed,
            "strategy": "popularity",
            "interaction_mode": INTERACTION_MODE,
            "disjoint_train_ratio": (
                DISJOINT_TRAIN_RATIO
            ),
            "selected_threshold": best_threshold,

            "val_auc": val_metrics["auc"],
            "val_ap": val_metrics["ap"],
            "val_f1_macro": (
                val_metrics["f1-macro"]
            ),

            "test_auc": test_metrics["auc"],
            "test_ap": test_metrics["ap"],
            "test_f1_macro": (
                test_metrics["f1-macro"]
            ),
            "test_f1_binary": (
                test_metrics["f1-binary"]
            ),
            "test_precision": (
                test_metrics["precision"]
            ),
            "test_recall": (
                test_metrics["recall"]
            ),
        }

        dataset_results.append(result)
        all_results.append(result)

        print(
            f"Threshold: {best_threshold:.4f} | "
            f"Test AUC: {test_metrics['auc']:.4f} | "
            f"AP: {test_metrics['ap']:.4f} | "
            f"Macro-F1: "
            f"{test_metrics['f1-macro']:.4f}"
        )

    # Save one CSV per dataset.
    dataset_df = pd.DataFrame(
        dataset_results
    )

    output_dir = os.path.join(
        get_base_dir(),
        dataset_name,
        "results",
        "link_prediction",
    )

    os.makedirs(
        output_dir,
        exist_ok=True,
    )

    output_path = os.path.join(
        output_dir,
        "popularity_baseline.csv",
    )

    dataset_df.to_csv(
        output_path,
        index=False,
    )

    print(
        f"\nSaved to: {output_path}"
    )


# ============================================================
# Final summary
# ============================================================

results_df = pd.DataFrame(all_results)

summary = (
    results_df
    .groupby("dataset_name")
    .agg(
        test_auc_mean=("test_auc", "mean"),
        test_auc_std=("test_auc", "std"),
        test_ap_mean=("test_ap", "mean"),
        test_ap_std=("test_ap", "std"),
        test_f1_macro_mean=(
            "test_f1_macro",
            "mean",
        ),
        test_f1_macro_std=(
            "test_f1_macro",
            "std",
        ),
    )
)

print("\n")
print("=" * 70)
print("FINAL SUMMARY")
print("=" * 70)

print(summary.to_string())