import os
import time
import pandas as pd
import torch
from torch_geometric.nn import to_hetero
from floppy import FLOPpyTracker

from src.dataset.dataset_loader_relationwise import build_heterodata_full, split_heterodata
# from src.dataset.dataset_loader import build_heterodata_full, split_heterodata
# from src.dataset.dataset_loader_memory_efficient import build_heterodata_full, split_heterodata
from src.models.encoder import GATEncoder
from src.models.decoder import EdgeDecoder
from src.models.link_predictor import HeteroGATLinkPredictor
from src.support.arguments import parse_arguments
from src.support.utils import set_random_seed, get_device, get_base_dir #, validate_heterodata_indices
from src.support.path_masking import get_interaction_metapath, get_positive_pairs, merge_positive_pairs, mask_witness_paths
from src.trainer import train_link_predictor, eval_link_predictor, find_best_threshold



import warnings
warnings.simplefilter('ignore')


args = parse_arguments()

seed = args.seed
set_random_seed(seed)

# data parameters
dataset_name = args.dataset_name
interaction_mode = args.interaction_mode
path_mask = args.path_mask
val_ratio = args.val_ratio
test_ratio = args.test_ratio
disjoint_train_ratio = args.disjoint_train_ratio
eval_neg_ratio = args.eval_neg_ratio

# model parameters
hidden_channels = args.hidden_channels
num_layers = args.num_layers
dropout = args.dropout

#training parameters
learning_rate = args.learning_rate
weight_decay = args.weight_decay
num_epochs = args.n_epochs
patience = args.patience
epsilon = args.epsilon
threshold_metric = args.threshold_metric


# negative sampling parameters
negative_mode = args.negative_mode
negative_strategy = args.negative_strategy if negative_mode=="dynamic" else "random"
train_neg_ratio = 0.0 if negative_mode == "none" else args.train_neg_ratio
negative_resample_every = 5 # solo dynamic

# Mixed random/semi-hard configuration
semi_hard_fraction = 0.5
candidate_multiplier = 5
semi_hard_start_epoch = 20
semi_hard_lower_quantile = 0.70
semi_hard_upper_quantile = 0.95
self_adversarial_alpha = 1.0
structure_max_attempts_multiplier = 20

mixed_strategy_names = {"mixed", "mixed_self_adversarial", "mixed_structure_aware"}


#others
device = torch.device(get_device() if torch.cuda.is_available() else "cpu")
output_dir = os.path.join(get_base_dir(), dataset_name, "results", "link_prediction")
os.makedirs(output_dir,exist_ok=True)


# BUILD DATA

data, tgt_edge_type, rev_tgt_edge_type = build_heterodata_full(dataset_name, interaction_mode)

# validate_heterodata_indices(data, data_name="full_data")

# The dynamic/static samplers must exclude every known positive pair, including validation and test positives.
all_positive_edge_index = data[tgt_edge_type].edge_index.detach().cpu().clone()

train_data, val_data, test_data = split_heterodata(
    data=data,
    target_edge_type=tgt_edge_type,
    reverse_target_edge_type=rev_tgt_edge_type,
    val_ratio=val_ratio,
    test_ratio=test_ratio,
    eval_neg_sampling_ratio=eval_neg_ratio,
    disjoint_train_ratio=disjoint_train_ratio
)

# validate_heterodata_indices(train_data, data_name="train_data")
# validate_heterodata_indices(val_data, data_name="val_data")
# validate_heterodata_indices(test_data, data_name="test_data")


# OPTIONAL PATH-MASKED EXPERIMENT
path_mask_diagnostics = {}

if path_mask:

    if interaction_mode == "any":
        raise ValueError("Path masking is defined for one interaction mode at a time.")

    selected_metapath = get_interaction_metapath(data=data, dataset_name=dataset_name, interaction_mode=interaction_mode)

    print("\n=== PATH-MASKED EXPERIMENT ===")
    print("Selected meta-path:")

    for edge_type in selected_metapath:
        print(f"  {edge_type}")

    # Retrieve positives generated by RandomLinkSplit
    train_positive_pairs = get_positive_pairs(train_data, tgt_edge_type)
    val_positive_pairs = get_positive_pairs(val_data, tgt_edge_type)
    test_positive_pairs = get_positive_pairs(test_data, tgt_edge_type)
    num_target_nodes = data[tgt_edge_type[2]].num_nodes

    # cumulative masking
    # train: remove paths for train supervision positives
    # val: remove train + validation paths
    # test: remove train + validation + test paths

    train_mask_pairs = train_positive_pairs
    val_mask_pairs = merge_positive_pairs(train_positive_pairs, val_positive_pairs, num_target_nodes=num_target_nodes)
    test_mask_pairs = merge_positive_pairs(train_positive_pairs,val_positive_pairs, test_positive_pairs, num_target_nodes=num_target_nodes)

    train_data, path_mask_diagnostics["train"] = mask_witness_paths(
            data=train_data,
            metapath=selected_metapath,
            positive_pairs=train_mask_pairs,
            split_name="train",
        )

    val_data, path_mask_diagnostics["val"] = mask_witness_paths(
            data=val_data,
            metapath=selected_metapath,
            positive_pairs=val_mask_pairs,
            split_name="val",
        )

    test_data, path_mask_diagnostics["test"] = mask_witness_paths(
            data=test_data,
            metapath=selected_metapath,
            positive_pairs=test_mask_pairs,
            split_name="test",
        )

    print("\nPath-mask diagnostics:")

    for split_name, diagnostics in path_mask_diagnostics.items():
        print(f"{split_name}: {diagnostics}")

# BUILD MODEL

encoder = GATEncoder(
    hidden_channels=hidden_channels,
    dropout=dropout,
    num_layers=num_layers
)

encoder = to_hetero(
    encoder,
    train_data.metadata(),
    aggr="sum"
)

decoder = EdgeDecoder(hidden_channels=hidden_channels)

model = HeteroGATLinkPredictor(
    encoder=encoder,
    decoder=decoder,
    edge_type=tgt_edge_type
)


# TRAINING

train_data = train_data.to(device)
val_data = val_data.to(device)
test_data = test_data.to(device)
model = model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
criterion = torch.nn.BCEWithLogitsLoss()

tracker = FLOPpyTracker(run_name="pytorch_experiment")
tracker.run(model=model, optimizer=optimizer, loss_fn=criterion)

start_time = time.time()

model, training_info = train_link_predictor(
    model=model,
    criterion=criterion,
    train_data=train_data,
    val_data=val_data,
    optimizer=optimizer,
    edge_type=tgt_edge_type,
    all_positive_edge_index=all_positive_edge_index,
    negative_mode=negative_mode,
    negative_strategy=negative_strategy,
    neg_sampling_ratio=train_neg_ratio,
    negative_resample_every=negative_resample_every,
    semi_hard_fraction=semi_hard_fraction,
    candidate_multiplier=candidate_multiplier,
    semi_hard_lower_quantile=semi_hard_lower_quantile,
    semi_hard_upper_quantile=semi_hard_upper_quantile,
    semi_hard_start_epoch=semi_hard_start_epoch,
    self_adversarial_alpha=self_adversarial_alpha,
    structure_max_attempts_multiplier=structure_max_attempts_multiplier,
    n_epochs=num_epochs,
    patience=patience,
    epsilon=epsilon
)

end_time = time.time()
training_time = end_time - start_time

print(f"Training time: {training_time:.2f} seconds")

report = tracker.report()


# Validation threshold
# Then, use validation data to select the threshold that maximizes the F1-score of the positive interaction class.
best_threshold, optimized_val_metrics, fixed_val_metrics = find_best_threshold(
    model=model,
    data=val_data,
    edge_type=tgt_edge_type,
    optimization_metric=threshold_metric
)

print("\nValidation threshold selection:")
print(
    f"Fixed threshold 0.5000 -> "
    f"F1-binary: {fixed_val_metrics['f1-binary']:.4f}, "
    f"Precision: {fixed_val_metrics['precision']:.4f}, "
    f"F1-macro: {fixed_val_metrics['f1-macro']:.4f}, "
    f"Recall: {fixed_val_metrics['recall']:.4f}"
)
print(
    f"Selected threshold {best_threshold:.4f} -> "
    f"F1-binary: {optimized_val_metrics['f1-binary']:.4f}, "
    f"F1-macro: {optimized_val_metrics['f1-macro']:.4f}, "
    f"Precision: {optimized_val_metrics['precision']:.4f}, "
    f"Recall: {optimized_val_metrics['recall']:.4f}"
)

#TEST

# Evaluate the trained model with the conventional fixed threshold.
test_fixed_metrics, test_scores = eval_link_predictor(
    model=model,
    data=test_data,
    edge_type=tgt_edge_type,
    threshold=0.5,
    return_scores=True
)

# Same trained model: the threshold selected on validation is now frozen and applied unchanged to the test set.
test_selected_metrics = eval_link_predictor(
    model=model,
    data=test_data,
    edge_type=tgt_edge_type,
    threshold=best_threshold,
    cached_scores=test_scores
)

print("\nTest metrics (fixed threshold=0.5000):")
for metric, value in test_fixed_metrics.items():
    print(f"{metric}: {value:.4f}")

print(f"\nTest metrics (validation-selected threshold={best_threshold:.4f}):")
for metric, value in test_selected_metrics.items():
    print(f"{metric}: {value:.4f}")


# SAVE RESULTS

result = {
    "dataset_name": dataset_name,
    "interaction_mode": interaction_mode,
    "seed": seed,
    "negative_mode": negative_mode,
    "negative_strategy": negative_strategy,
    "train_neg_ratio": train_neg_ratio,
    "eval_neg_ratio": eval_neg_ratio,
    "negative_resample_every": negative_resample_every,
    "semi_hard_fraction": semi_hard_fraction if negative_strategy in mixed_strategy_names else 0.0,
    "candidate_multiplier": candidate_multiplier if negative_strategy in mixed_strategy_names else 0.0,
    "semi_hard_start_epoch": semi_hard_start_epoch if negative_strategy in mixed_strategy_names else 0,
    "semi_hard_lower_quantile": semi_hard_lower_quantile if negative_strategy == "mixed" else 0.0,
    "semi_hard_upper_quantile": semi_hard_upper_quantile if negative_strategy == "mixed" else 0.0,
    "self_adversarial_alpha": self_adversarial_alpha if negative_strategy == "mixed_self_adversarial" else 0.0,
    "structure_max_attempts_multiplier": structure_max_attempts_multiplier if negative_strategy == "mixed_structure_aware" else 0,
    "disjoint_train_ratio": disjoint_train_ratio,
    "val_ratio": val_ratio,
    "test_ratio": test_ratio,
    "hidden_channels": hidden_channels,
    "num_layers": num_layers,
    "dropout": dropout,
    "learning_rate": learning_rate,
    "weight_decay": weight_decay,
    "best_epoch": training_info["best_epoch"],
    "epochs_trained": training_info["epochs_trained"],
    "best_val_auc": training_info["best_val_auc"],
    "selected_threshold": best_threshold,
    "training_time_seconds": training_time,
    "val_fixed_f1_binary": fixed_val_metrics["f1-binary"],
    "val_fixed_f1_macro": fixed_val_metrics["f1-macro"],
    "val_fixed_precision": fixed_val_metrics["precision"],
    "val_fixed_recall": fixed_val_metrics["recall"],
    "val_selected_f1_binary": optimized_val_metrics["f1-binary"],
    "val_selected_f1_macro": optimized_val_metrics["f1-macro"],
    "val_selected_precision": optimized_val_metrics["precision"],
    "val_selected_recall": optimized_val_metrics["recall"],
    "test_auc": test_selected_metrics["auc"],
    "test_ap": test_selected_metrics["ap"],
    "test_selected_f1_binary": test_selected_metrics["f1-binary"],
    "test_selected_f1_macro": test_selected_metrics["f1-macro"],
    "test_selected_precision": test_selected_metrics["precision"],
    "test_selected_recall": test_selected_metrics["recall"],
    "test_fixed_f1_binary": test_fixed_metrics["f1-binary"],
    "test_fixed_f1_macro": test_fixed_metrics["f1-macro"],
    "test_fixed_precision": test_fixed_metrics["precision"],
    "test_fixed_recall": test_fixed_metrics["recall"],
    "FLOPs_bwd": report.model_backward_flop,
    "BLOPs_bwd": report.model_backward_bop,
    "FLOPs_fwd": report.model_forward_flop,
    "BLOPs_fwd": report.model_forward_bop,
    "FLOPs_tot": report.overall_flop,
    "BLOPs_tot": report.overall_bop,

    "experiment": "path_masked" if path_mask else "standard",
    "path_mask": path_mask,
    "path_mask_train_edges_removed": path_mask_diagnostics.get("train", {}).get("edges_removed", 0),
    "path_mask_val_edges_removed": path_mask_diagnostics.get("val", {}).get("edges_removed", 0),
    "path_mask_test_edges_removed": path_mask_diagnostics.get("test", {}).get("edges_removed", 0),
    "path_mask_train_fraction_removed": path_mask_diagnostics.get("train", {}).get("fraction_edges_removed", 0.0),
    "path_mask_val_fraction_removed": path_mask_diagnostics.get("val", {}).get("fraction_edges_removed", 0.0),
    "path_mask_test_fraction_removed": path_mask_diagnostics.get("test", {}).get("fraction_edges_removed", 0.0)
}

#results_path = os.path.join(output_dir, "all_runs.csv")
results_filename = "all_runs_path_masked.csv" if path_mask else "all_runs.csv"
results_path = os.path.join(output_dir, results_filename)
new_result_df = pd.DataFrame([result])
if os.path.exists(results_path):
    results_df = pd.read_csv(
        results_path
    )

    results_df = pd.concat(
        [
            results_df,
            new_result_df,
        ],
        ignore_index=True,
    )
else:
    results_df = new_result_df


# Re-running the same experiment replaces the previous row.
results_df = (
    results_df
    .drop_duplicates(
        subset=[
            "dataset_name",
            "interaction_mode",
            "seed",
            "disjoint_train_ratio",
            "train_neg_ratio",
            "negative_mode",
            "negative_strategy",
            "self_adversarial_alpha",
            "structure_max_attempts_multiplier",
        ],
        keep="last",
    )
    .sort_values(
        by=[
            "dataset_name",
            "interaction_mode",
            "negative_mode",
            "negative_strategy",
            "disjoint_train_ratio",
            "train_neg_ratio",
            "seed",
        ]
    )
    .reset_index(drop=True)
)

results_df.to_csv(
    results_path,
    index=False
)

print(
    f"\nResults saved to "
    f"{os.path.abspath(results_path)}"
)
